### ISSUE TITLE
failed to run example: ImportError: dlopen(/Users/dev/.local/lib/python2.7/site-packages/freenect2/_freenect2.so, 2): Symbol not found: __ZN12libfreenect29Freenect210openDeviceERKSs

### ISSUE THREAD

**Issue by mfkenson** [rjw57/freenect2-python#1]
I followed the installation steps on https://rjw57.github.io/freenect2-python/

The example `Protonect` from libfreenect2 runs fine.

I created a simple.py script according to the `Simple usage` in the website.
Encountered the following error
```

Traceback (most recent call last):
  File "simple.py", line 7, in <module>
    from freenect2 import Device, FrameType
  File "/Users/dev/.local/lib/python2.7/site-packages/freenect2/__init__.py", line 10, in <module>
    from ._freenect2 import lib, ffi
ImportError: dlopen(/Users/dev/.local/lib/python2.7/site-packages/freenect2/_freenect2.so, 2): Symbol not found: __ZN12libfreenect29Freenect210openDeviceERKSs
  Referenced from: /Users/dev/.local/lib/python2.7/site-packages/freenect2/_freenect2.so
  Expected in: flat namespace
 in /Users/dev/.local/lib/python2.7/site-packages/freenect2/_freenect2.so

**Comment by rahul-iyer** [comment]
@mfkenson Were you able to figure out the solution?
